version: "3"

services:

  hello:
    image: hello-service
    build: ./hello-service/
    ports:
      - 7001:9001
    environment:
         - SSR_CLIENT_PORT=9001
         - SSR_CLIENT_HOST=hello
         - SSR_REGISTRY_PORT=9999
         - SSR_REGISTRY_HOST=registry
    networks:
      - example-network

  world:
     image: world-service
     build: ./world-service/
     ports:
       - 7002:9002
     environment:
          - SSR_CLIENT_PORT=9002
          - SSR_CLIENT_HOST=world
          - SSR_REGISTRY_PORT=9999
          - SSR_REGISTRY_HOST=registry
     networks:
       - example-network

  registry:
    image: registry-server
    build: ./registry-server/
    ports:
      - 5555:9999
    networks:
      - example-network

networks:
  example-network:
    driver: bridge